name = "Quantics"
uuid = "87f76fb3-a40a-40c9-a63c-29fcfe7b7547"
authors = ["Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]
version = "0.4.6"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
FastMPOContractions = "f6e391d2-8ffa-4d7a-98cd-7e70024481ca"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuanticsTCI = "b11687fd-3a1c-4c41-97d0-998ab401d50e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
PartitionedMPSs = "17ce1de9-5131-45e3-8a48-9723b6e2dc23"

[extensions]
QuantiscPartitionedMPSsExt = "PartitionedMPSs"

[compat]
EllipsisNotation = "1"
FastMPOContractions = "^0.2.2"
ITensorMPS = "0.3.1"
ITensors = "0.7, 0.8, 0.9"
PartitionedMPSs = "0.5.2, 0.6"
QuanticsTCI = "0.7"
SparseIR = "^0.96, 0.97, 1"
StaticArrays = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"
QuanticsTCI = "b11687fd-3a1c-4c41-97d0-998ab401d50e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
TensorCrossInterpolation = "b261b2ec-6378-4871-b32e-9173bb050604"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "ReTestItems", "Aqua", "PartitionedMPSs", "TensorCrossInterpolation", "QuanticsTCI", "QuanticsGrids", "SparseIR"]
